USE [master]
GO

/****** Object:  Database [BD_Corporación]    Script Date: 10/15/2017 6:34:25 PM ******/
CREATE DATABASE [BD_Corporación]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BD_Corporación', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\BD_Corporación.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BD_Corporación_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\BD_Corporación_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BD_Corporación] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BD_Corporación].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BD_Corporación] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BD_Corporación] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BD_Corporación] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BD_Corporación] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BD_Corporación] SET ARITHABORT OFF 
GO

ALTER DATABASE [BD_Corporación] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BD_Corporación] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BD_Corporación] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BD_Corporación] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BD_Corporación] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BD_Corporación] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BD_Corporación] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BD_Corporación] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BD_Corporación] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BD_Corporación] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BD_Corporación] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BD_Corporación] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BD_Corporación] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BD_Corporación] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BD_Corporación] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BD_Corporación] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BD_Corporación] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BD_Corporación] SET RECOVERY FULL 
GO

ALTER DATABASE [BD_Corporación] SET  MULTI_USER 
GO

ALTER DATABASE [BD_Corporación] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BD_Corporación] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BD_Corporación] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BD_Corporación] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BD_Corporación] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BD_Corporación] SET  READ_WRITE 
GO

USE [BD_Corporación]
GO

/****** Object:  Table [dbo].[AGUINALDO]    Script Date: 10/15/2017 6:34:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AGUINALDO](
	[id_aguinaldo] [int] NOT NULL,
	[id_empleado] [int] NULL,
	[id_planta] [int] NULL,
	[monto] [decimal](19, 6) NULL,
 CONSTRAINT [PK_AGUINALDO] PRIMARY KEY CLUSTERED 
(
	[id_aguinaldo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/****** Object:  Table [dbo].[EMPLEADO]    Script Date: 10/15/2017 6:35:13 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EMPLEADO](
	[id_empleado] [int] NOT NULL,
	[id_planta] [int] NOT NULL,
	[nombre] [nvarchar](15) NULL,
	[apellidos] [nvarchar](30) NULL,
	[fecha_ingreso] [date] NULL,
	[fecha_salida] [date] NULL,
	[id_supervisor] [int] NULL,
 CONSTRAINT [PK_EMPLEADO] PRIMARY KEY CLUSTERED 
(
	[id_empleado] ASC,
	[id_planta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [BD_Corporación]
GO

/****** Object:  Table [dbo].[PAGO_PLANILLAS]    Script Date: 10/15/2017 6:35:23 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PAGO_PLANILLAS](
	[id_pago] [int] NOT NULL,
	[id_planilla] [int] NULL,
	[fecha] [date] NULL,
 CONSTRAINT [PK_PAGO_PLANILLAS] PRIMARY KEY CLUSTERED 
(
	[id_pago] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [BD_Corporación]
GO

/****** Object:  Table [dbo].[HISTORIAL_PLANILLAS]    Script Date: 10/16/2017 3:11:31 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[HISTORIAL_PLANILLAS](
	[id_planilla] [int] NOT NULL,
	[id_empleado] [int] NULL,
	[id_planta] [int] NULL,
	[salario_bruto] [decimal](19, 6) NULL,
	[salario_neto] [decimal](19, 6) NULL,
	[fecha] [date] NULL,
 CONSTRAINT [PK_PLANILLA] PRIMARY KEY CLUSTERED 
(
	[id_planilla] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/************ Foreign Keys **************/


/***AGUINALDO***/
ALTER TABLE [dbo].[AGUINALDO]  WITH CHECK ADD  CONSTRAINT [FK_AGUINALDO_EMPLEADO] FOREIGN KEY([id_empleado], [id_planta])
REFERENCES [dbo].[EMPLEADO] ([id_empleado], [id_planta])
GO

ALTER TABLE [dbo].[AGUINALDO] CHECK CONSTRAINT [FK_AGUINALDO_EMPLEADO]
GO

/****PAGO_PLANILLAS****/

ALTER TABLE [dbo].[PAGO_PLANILLAS]  WITH CHECK ADD  CONSTRAINT [FK_PAGO_PLANILLAS_PLANILLA] FOREIGN KEY([id_planilla])
REFERENCES [dbo].[HISTORIAL_PLANILLAS] ([id_planilla])
GO

ALTER TABLE [dbo].[PAGO_PLANILLAS] CHECK CONSTRAINT [FK_PAGO_PLANILLAS_PLANILLA]
GO


/****HISTORIAL_PLANILLAS****/

ALTER TABLE [dbo].[HISTORIAL_PLANILLAS]  WITH CHECK ADD  CONSTRAINT [FK_PLANILLA_EMPLEADO2] FOREIGN KEY([id_empleado], [id_planta])
REFERENCES [dbo].[EMPLEADO] ([id_empleado], [id_planta])
GO

ALTER TABLE [dbo].[HISTORIAL_PLANILLAS] CHECK CONSTRAINT [FK_PLANILLA_EMPLEADO2]
GO
